export const routes = {
  root: '/',
  main: '/main',
  login: '/login',
  register: '/register',
  admin: '/admin',
  myTickets: '/my-tickets',
  editUser: '/edit-user',
  adminAddTrain: '/admin/add-train',
  adminEditTrain: '/admin/edit-train',
  adminAddRoute: '/admin/add-route',
  adminEditRoute: '/admin/edit-route',
  adminAddVoyage: '/admin/add-voyage',
  adminEditVoyage: '/admin/edit-voyage',
};
